### PR TITLE
Add autogenerated documentation

### PR DESCRIPTION
**Pull request by dtemkin-volpe**
This should be a completed version of the autogenerated docs. The prior iteration had a bug where it would always open a pull request on the main branch, but that should be fixed. Please let me know if there are any issues, thanks! 

@ssmith55 @ianberg-volpe

### CODE REVIEW

**Comment by ssmith55** [comment]
It is looking good.  I was able to make and edit (this time to lane.schema.josn), and it carried through to the Markdown.  Back in the GMNS repository, I made a tag (v.0.95) on the main branch, and downloaded a zipfile of the development branch.  Ian, your thoughts on merging this into GMNS / develop?  Thanks.

**Review by ssmith55 — APPROVED** [review]
Looks good.   Would be nice to replace those "schema" headers.  After this is merged, will want to do some more testing in the gmns develop branch.

**Comment by dtemkin-volpe** [comment]
@ssmith55 Fixed the `schema` header, should be replaced with the file name itself (along with adding a few details about the schema).

**Review by ianberg-volpe — APPROVED** [review]
I'm good with merging to develop. We can continue to refine there if we need to make additional changes.

**Pull request merged**
